version: '3.8'

services:
  db:
    restart: unless-stopped
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    build: .
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    restart: always
    image: nginx:1.21.3-alpine

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/cert.crt:/etc/nginx/ssl/cert.crt
      - ./ssl/cert.key:/etc/nginx/ssl/cert.key
      - static_value:/var/html/static/
      - media_value:/var/html/media/

    depends_on:
      - web

  celery:
    build: .
    restart: unless-stopped
    command: celery -A notification worker -l info
    volumes:
      - .:/app
    depends_on:
      - web
      - redis

  celery-beat:
    build: .
    restart: unless-stopped
    command: celery -A notification beat -l info
    volumes:
      - .:/app
    depends_on:
      - web
      - redis

  redis:
    restart: unless-stopped
    image: redis

  flower:
    build: .
    command: celery -A notification --broker=redis://redis:6379/0 flower
    ports:
      - "5555:5555"
    depends_on:
      - celery

volumes:
  static_value:
  media_value: